### PR TITLE
FTX Support, Async Requests, Major Re-Write, Possible Fork?

### PR DESCRIPTION
**Pull request by cdalton713**
I took your idea and kinda ran with it... this new version is majorly re-written and supports multiple exchanges.  Currently, FTX and Binance are available.  Additional exchanges can be easily added by subclassing the `Broker` ABC and following the wrapper structure used.

This is a major re-write, I'm not sure if you'd be interested in it.  If not, I'll continue on with my fork.  

I lost track of all of the changes I made, but broad strokes:
- It's now object-oriented
- multiple exchanges now allowed
- more verbose logging
- basic FTX testing
- now async
- redid config yml for multiple settings per exchange

Todo:
- swap to multithreaded?
- further testing / Binance tests
- I haven't had a new coin populate yet, so may still be a bug or two there

### CODE REVIEW

**Comment by pluja** [comment]
Your fork is pretty nice. There are some interesting PRs here, you could consider merging some of them to your code.

**Comment by Emilvang** [comment]
Does this one fix the volume spam on issue #22?

**Comment by cdalton713** [comment]
> Does this one fix the volume spam on issue #22?

I haven't had a live order yet, but I don't think it'll be an issue.  My output is pretty different from the original ones, and both the test mode and live modes return information in the exact same format.  Additionally, Binance offers a 'test order' query-path to double check the parameters are valid - this unit test is passing.

**Comment by cdalton713** [comment]
> Your fork is pretty nice. There are some interesting PRs here, you could consider merging some of them to your code.

Thanks! Yes that's definitely on my to-do list.  Hopefully this weekend...

**Comment by antonevane** [comment]
Please remove all IDEA files and add the `.idea/` directory to the `.gitignore`.

**Pull request closed without merging**
